#!/usr/bin/env python3
"""Export the English copy of the v2 dataset.

    python scripts/export_english_view.py path/to/dental_clinical_dataset_v2 \
        --outdir english_view

This script produces the paired English copy from the combined v2 build: each
record keeps its structured fields and the eight ``*_en`` translation fields,
and drops the Chinese narratives. Radiographs are not copied by default;
``image_file`` still names the paired image file.

Deliberate properties of the view, stated in the README it writes:

* Field names keep the ``_en`` suffix, so it stays obvious that every
  narrative is a reviewed translation, not source text.
* Protected tokens (bracketed billing strings, drug brand names) appear in
  their original script even in the English fields, by design.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

STRUCTURED = (
    "patient_id", "image_file", "has_image", "age", "sex",
    "attending_physician", "chief_complaint_category", "treatment_category",
    "primary_diagnosis_icd",
)
SEX_EN = {"\u7537": "male", "\u5973": "female", "male": "male", "female": "female"}

README = """\
# English copy of dental_clinical_dataset_v2

This folder is the English language copy, generated by
`scripts/export_english_view.py` from the combined v2 build.

Each JSON record keeps the structured fields and the eight `*_en` fields
holding English translations of the clinical narratives. The `_en` suffix is
kept on purpose: every narrative here is a reviewed English translation, not
source text. Translation validation is reported in the paper, and all
identified errors from the review workflow were corrected before release.

Protected tokens (bracketed billing/drug strings, brand names) appear in
their original script by design. `image_file` refers to
`panoramic_radiographs/` in the main archive.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("dataset", type=Path)
    ap.add_argument("--outdir", type=Path, default=Path("english_view"))
    args = ap.parse_args()

    recdir = args.outdir / "clinical_records"
    recdir.mkdir(parents=True, exist_ok=True)
    n = 0
    for f in sorted((args.dataset / "clinical_records").glob("*.json")):
        rec = json.loads(f.read_text(encoding="utf-8"))
        out = {k: rec[k] for k in STRUCTURED if k in rec}
        out["sex"] = SEX_EN.get(rec.get("sex"), rec.get("sex"))
        out.update({k: v for k, v in rec.items() if k.endswith("_en")})
        (recdir / f.name).write_text(
            json.dumps(out, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8")
        n += 1
    meta = args.dataset / "metadata.csv"
    if meta.exists():
        with meta.open("r", encoding="utf-8-sig", newline="") as fh:
            reader = csv.DictReader(fh)
            rows = list(reader)
            fieldnames = reader.fieldnames or []
        for row in rows:
            row["sex"] = SEX_EN.get(row.get("sex"), row.get("sex"))
        with (args.outdir / "metadata.csv").open("w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=fieldnames, lineterminator="\n")
            writer.writeheader()
            writer.writerows(rows)
    (args.outdir / "README.md").write_text(README, encoding="utf-8")
    print(f"wrote {n} English-copy records to {args.outdir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
