#!/usr/bin/env python3
"""Generate the Data Records tables of the descriptor from a release copy.

    PYTHONPATH=code/src python code/scripts/make_descriptor_tables.py \
        dataset/dental_clinical_dataset_v3/dental_clinical_dataset_v3_zh \
        --outdir submission_package/tables

Writes three LaTeX fragments and a JSON with every number they contain:

* ``table_completeness.tex`` -- per-field non-empty counts for the 17
  released fields, plus the count of narrative values that are only a
  placeholder such as 无 / 暂无 ("none" / "not yet").
* ``table_icd.tex`` -- the 28 ICD-10 code atoms with record counts and the
  precision at which each is released (three-character category with ``.x``,
  three-character code, or four-character subcategory).
* ``table_style.tex`` -- simple per-physician documentation measures:
  median narrative length, median length of three narrative fields, a
  moving-average type-token ratio over characters (window 100), and the
  density of shorthand tokens (Latin-letter abbreviations, ``#``-prefixed
  tooth numbers, bracketed +/- signs, Roman-numeral grades) per 100
  characters.

The measures are descriptive; no hypothesis test is performed.
"""

from __future__ import annotations

import argparse
import json
import re
import statistics
from collections import Counter
from pathlib import Path

NARRATIVE = [
    "chief_complaint", "history_of_present_illness", "oral_examination",
    "imaging_examination", "primary_diagnosis", "treatment_plan",
    "procedure", "physician_advice",
]
FIELD_ORDER = [
    "patient_id", "image_file", "has_image", "age", "sex", "attending_physician",
    "chief_complaint", "chief_complaint_category", "history_of_present_illness",
    "oral_examination", "imaging_examination", "primary_diagnosis",
    "primary_diagnosis_icd", "treatment_category", "treatment_plan", "procedure",
    "physician_advice",
]
PLACEHOLDER = re.compile(r"^\s*(无|暂无|留空|无特殊|-|—|无异常|未见异常|/|\.|待定)\s*[。.]?\s*$")
SHORTHAND = re.compile(r"[A-Za-z]{2,}|#\d{1,2}|[（(][+\-±]{1,2}[)）]|[Ⅰ-Ⅲ]|[0-9]°")
PHYSICIANS = ["P1", "P2", "P3", "P4", "P5"]


def tex(s: str) -> str:
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


def load(copy_dir: Path) -> list[dict]:
    return [json.loads(p.read_text(encoding="utf-8"))
            for p in sorted((copy_dir / "clinical_records").glob("*.json"))]


def completeness(recs: list[dict]) -> list[dict]:
    rows = []
    for f in FIELD_ORDER:
        vals = [str(r.get(f) if r.get(f) is not None else "").strip() for r in recs]
        non_empty = sum(1 for v in vals if v)
        placeholder = sum(1 for v in vals if v and PLACEHOLDER.match(v)) if f in NARRATIVE else None
        rows.append({"field": f, "non_empty": non_empty,
                     "placeholder_only": placeholder,
                     "informative": non_empty - (placeholder or 0)})
    return rows


def icd_table(recs: list[dict]) -> list[dict]:
    counts: Counter[str] = Counter()
    for r in recs:
        for a in str(r.get("primary_diagnosis_icd") or "").split(";"):
            a = a.strip()
            if a:
                counts[a] += 1
    rows = []
    for code, n in counts.most_common():
        if code.endswith(".x"):
            prec = "category (.x)"
        elif "." in code:
            prec = "subcategory"
        else:
            prec = "category"
        rows.append({"code": code, "records": n, "precision": prec})
    return rows


def mattr(s: str, w: int = 100) -> float:
    if len(s) <= w:
        return len(set(s)) / max(len(s), 1)
    vals = [len(set(s[i:i + w])) / w for i in range(0, len(s) - w + 1, 10)]
    return sum(vals) / len(vals)


def style(recs: list[dict]) -> list[dict]:
    rows = []
    for p in PHYSICIANS:
        rs = [r for r in recs if r.get("attending_physician") == p]
        if not rs:
            continue

        def med(field: str) -> float:
            return statistics.median(len(str(r.get(field) or "")) for r in rs)

        total = [sum(len(str(r.get(f) or "")) for f in NARRATIVE) for r in rs]
        pooled = "".join("".join(str(r.get(f) or "") for f in NARRATIVE) for r in rs)
        rows.append({
            "physician": p, "n": len(rs),
            "median_total_chars": statistics.median(total),
            "median_hpi": med("history_of_present_illness"),
            "median_oral_exam": med("oral_examination"),
            "median_imaging": med("imaging_examination"),
            "mattr_100": round(mattr(pooled), 3),
            "shorthand_per_100": round(100 * len(SHORTHAND.findall(pooled)) / len(pooled), 2),
        })
    return rows


def write_tables(outdir: Path, comp: list[dict], icd: list[dict], sty: list[dict], n: int) -> None:
    outdir.mkdir(parents=True, exist_ok=True)

    lines = [r"% Generated by code/scripts/make_descriptor_tables.py -- do not edit by hand.",
             r"\begin{tabular}{lrr}", r"\toprule",
             r"Field & Non-empty & Placeholder only \\", r"\midrule"]
    for r in comp:
        ph = "---" if r["placeholder_only"] is None else str(r["placeholder_only"])
        lines.append(f"\\texttt{{{tex(r['field'])}}} & {r['non_empty']} & {ph} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    (outdir / "table_completeness.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    half = (len(icd) + 1) // 2
    left, right = icd[:half], icd[half:]
    lines = [r"% Generated by code/scripts/make_descriptor_tables.py -- do not edit by hand.",
             r"\begin{tabular}{lrl@{\hspace{2em}}lrl}", r"\toprule",
             r"Code & Records & Precision & Code & Records & Precision \\", r"\midrule"]
    for i in range(half):
        a = left[i]
        b = right[i] if i < len(right) else None
        cell_a = f"{a['code']} & {a['records']} & {a['precision']}"
        cell_b = f"{b['code']} & {b['records']} & {b['precision']}" if b else " & & "
        lines.append(f"{cell_a} & {cell_b} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    (outdir / "table_icd.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    lines = [r"% Generated by code/scripts/make_descriptor_tables.py -- do not edit by hand.",
             r"\begin{tabular}{lrrrrrrr}", r"\toprule",
             r"Physician & Records & Narrative (chars) & HPI & Oral exam & Imaging & MATTR$_{100}$ & Shorthand /100 chars \\",
             r"\midrule"]
    for r in sty:
        lines.append(f"{r['physician']} & {r['n']} & {r['median_total_chars']:.1f} & "
                     f"{r['median_hpi']:.1f} & {r['median_oral_exam']:.1f} & "
                     f"{r['median_imaging']:.1f} & {r['mattr_100']:.3f} & "
                     f"{r['shorthand_per_100']:.2f} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    (outdir / "table_style.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    (outdir / "descriptor_tables.json").write_text(json.dumps({
        "n_records": n, "completeness": comp, "icd": icd, "style": sty,
        "icd_precision_counts": dict(Counter(r["precision"] for r in icd)),
    }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("copy", type=Path, help="Chinese source copy of the release")
    ap.add_argument("--outdir", type=Path, default=Path("tables"))
    args = ap.parse_args()
    recs = load(args.copy)
    comp, icd, sty = completeness(recs), icd_table(recs), style(recs)
    write_tables(args.outdir, comp, icd, sty, len(recs))
    print(f"{len(recs)} records; {len(icd)} ICD atoms "
          f"({Counter(r['precision'] for r in icd)}); wrote 3 tables to {args.outdir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
